### ISSUE TITLE
List of gratitude-cards

### ISSUE THREAD

**Issue by yvonneadam** [yvonneadam/capstone-project#1]
## Value Proposition

**As a** user aka gratitude seeker
**I need** a list
**to be able to** see what I am (and already was) grateful for.

## Description
<img width="200" alt="first-user-story" src="https://user-images.githubusercontent.com/106114808/179449933-c9b867fb-db98-4a97-9db8-2fcb8bf4b828.png">

## Acceptance Criteria

- [x] There is a list of written gratitude cards 
- [x] Each card shows the datum and the short description for what the user was grateful for
- [x] List of cards is scrollable
- [x] There is a headline question called "Wofür bist du heute dankbar?"

## Tasks

(for developers team)

- [x] Create components/cards
- [x] Prepare a heading 
- [x] Create global styles
- [x] Add to Storybook
- [x] Write tests
- [x] Create db.js with gratitude statements
- [x] Add to app

**Comment by PReichetanz** [comment]
Hi Yvonne,

this looks really good! 🎉

As you mentioned, I assume this will be your first story to implement, so let's discuss some ideas: 💬

- Regarding the form: I don't see a submit button nor a label for the input, where do you want to place them?
  - I could imagine that the label is screen reader only because the heading is clear enough about what to do here.
- If this is your first user story, you don't have a second page yet; this means your Link to the main page shouldn't be here.
  - You can display the content if the input - after clicking the submit button - underneath the form.
  - In a following user story, you can add this content to the main page after submit (or whereever you want to display it).
