### ISSUE TITLE
Date (of today) automatically shown in TopNav

### ISSUE THREAD

**Issue by yvonneadam** [yvonneadam/capstone-project#11]
## Value Proposition

**As a** ...user
**I need** ...the day of today
**to be able to** ...see the date of the day immediately and automatically.

## Description

<img width="200" alt="top nav bar" src="https://user-images.githubusercontent.com/106114808/182438229-c3970108-dd97-489d-939c-af7b36ba9a94.png">

## Acceptance Criteria

- [x] The date of the day has to be shown 
- [x] It will be the date of today's day, written in the following layout (for example): Thursday, 04.08.2022 
- [x] (the calendar symbol on the right side is for another user story, pls ignore here)

## Tasks

(for developers team)

- [x] Create feature branch
- [x] Create component
- [x] Using a library in React to fill in the date automatically when open the app
- [x] Update components
- [x] Create styled components
- [x] Write tests
- [x] Storybook

**Comment by mbosselmann** [comment]
Hey Yvonne,
I really like your user story. 👍  I only have two remarks:

**Description**
On the right we can also see a monthly calendar view. I think this will be too small for users to see or? 🤔 Therefore, I just asked myself if it is necessary to implement this? 

**Acceptance criteria**
"Using a library in React to fill in the date automatically when open the app" - This is not a criterion that a user will see. This is an implementation detail and should be moved to tasks.
