### ISSUE TITLE
Input form for gratitude journal

### ISSUE THREAD

**Issue by yvonneadam** [yvonneadam/capstone-project#2]
## Value Proposition

**As a**  user
**I need** an input field/form 
**to be able to** write what I am grateful for today.

## Description
<img width="200" alt="user story 2" src="https://user-images.githubusercontent.com/106114808/179961016-1941f43b-e983-4e80-9d0a-76e2522df986.png">

## Acceptance Criteria

- [x] Create a form for those inputs
- [x] There is an heading question called "Wofür bist du heute dankbar?" (it stays the same one every single day)
- [x] There is a button <cancel> in case the user decides to write it later --> form stays empty
- [x] There is a button <save> in case the written text should be saved --> text runs into the list from yvonneadam/capstone-project#1 
- [x] There is a cursor and a keyboard as components of an input field

## Tasks

(for developers team)

- [x] Create feature branch
- [x] Create components/buttons
- [x] Update components/link to yvonneadam/capstone-project#1 
- [x] Create global styles
- [x] Write Storybook
- [x] Write tests

**Comment by chris-yooo** [comment]
hey yvi,

one question from me:
now you have added a button at the bottom to go back to the input. is now the main page your input field and if you clicked save there you get to the second page with your gratitudes ?

or is the main page still your gratitude and the input form your second input page ?

if the latter is true then call the button below "create gratitude". and then it should be in the "Acceptance Criteria's" and in the dev area :)

maybe [ ] There is a button to open my Input Site
and [ ] create button nav to Input site

chris
