### ISSUE TITLE
input dates

### ISSUE THREAD

**Issue by yvonneadam** [yvonneadam/capstone-project#3]
## Value Proposition

**As a** user
**I want to** type the date of the day in my gratitude journal form,
**so that** I know which day it was I was grateful for this or that.

## Description

<img width="200" alt="date input" src="https://user-images.githubusercontent.com/106114808/180024868-5a251947-5acd-4f61-b040-9e9364198fc3.png">

## Acceptance Criteria

- [x] Create an extra input field for the date
- [x] Placeholder text <date of today> (later on with calendar function date will be automatically shown)
- [x] On screen 2: date is linked to text the user was written in the form
- [x] The newest input will shown as the top level date/text on screen 2

## Tasks

(for developers team)

- [x] Create feature branch
- [x] Create components/input form
- [x] Update components/list of gratitude texts
- [x] Add to Storybook
- [x] Write tests

**Comment by chris-yooo** [comment]
hey yvi long day so far ... the extra input field is the date in the upper of the left picture ? check

in example i have to write down the date ? or i can fill the date with a popup calendar ?

or i have to put in 19.7.2022 and the input automatically change to Dienstag, .....

if you have cleared up this ambiguity nothing should stand in the way :)

chris

**Comment by yvonneadam** [comment]
Pop up calendar sounds great to me, I'll try to code this 😃

Thanks for your ideas and so it's home time now 🍦

**Comment by chris-yooo** [comment]
https://stackoverflow.com/questions/68657646/react-big-calendar-how-make-a-popup-with-onselectevent

:)

**Comment by chris-yooo** [comment]
i found a little thing for you :D: https://blog.logrocket.com/react-calendar-tutorial-build-customize-calendar/

**Comment by PReichetanz** [comment]
Hi Yvonne,

I just have one thing to mention: Please make sure your date input has a proper label so that the user knows what he/she has to write into this field.
