### ISSUE TITLE
Form(+functionality)

### ISSUE THREAD

**Issue by yvonneadam** [yvonneadam/capstone-project#6]
## Value Proposition

**As a** ...user
**I need** ... a form
**to be able to** ...type my daily messages I am grateful for and to see them in a list combined with the date of input.

## Description
<img width="200" alt="Formfunctionality" src="https://user-images.githubusercontent.com/106114808/181309503-9f54b809-cee7-47dd-a441-d10ffd2895fe.png">

## Acceptance Criteria

- [x] form element
- [x] date field with placeholder date
- [x] text field
- [x] submit button
- [x] keypad pops up (later on: color of text, typo can be changed individually)

## Tasks

(for developers team)

- [x] Create feature branch
- [x] Write components/form hook 
- [x] Use Storybook
- [x] Practice on testing

**Comment by julialoeschel** [comment]
Hey Yvonne, great.
for me the `... ` in Value Proposition is not necessary (please keep it if all of your other stories are like that ;) )
also Im asking myself if you want to prevent an empty submit (I think that would be useful).

other than that - good story 👍
