### ISSUE TITLE
Top navigation bar for date & calendar on click

### ISSUE THREAD

**Issue by yvonneadam** [yvonneadam/capstone-project#8]
## Value Proposition

**As a** ...user
**I need** ...a top navigation bar
**to be able to** ...see the date of the day and the calendar symbol immediately.

## Description

<img width="200" alt="top nav bar" src="https://user-images.githubusercontent.com/106114808/182438229-c3970108-dd97-489d-939c-af7b36ba9a94.png">

## Acceptance Criteria

- [x] There has to be a seperate bar to navigate
- [x] The date of the day has to be shown 
- [x] There will be a button click for calendar
- [x] on point: date and calendar symbol

## Tasks

(for developers team)

- [x] Create feature branch
- [x] Create component
- [x] Update components
- [x] Create styled components
- [x] Add react router
- [x] Write tests
- [x] Storybook

**Comment by ahohnsen** [comment]
Hey Yvonne,

Nicely done 🚀 

I have a few questions:

> There will be a button click for calendar
What happens after clicking on the calendar? I would suggest to be a bit more specific, e.g.: _By clicking on the calendar icon a calendar will appear, so that the user can choose a specific date._

As well, I do not really understand, what you mean by the following:

> on point: date and calendar symbol

Do you mean, that the navigation is fixed at the top of the screen?

**Comment by yvonneadam** [comment]
Thank you for your great ideas, I will implement that in the next user story related to my calendar.
