### ISSUE TITLE
Bottom navigation bar for seperate pages

### ISSUE THREAD

**Issue by yvonneadam** [yvonneadam/capstone-project#9]
## Value Proposition

**As a** ...user
**I need** ...a bottom navigation bar
**to be able to** ...see the different pages by symbol immediately.

## Description
<img width="200" alt="Bildschirmfoto 2022-08-02 um 19 33 32" src="https://user-images.githubusercontent.com/106114808/182439475-6e30eb6c-3443-4c53-b71b-8d5ab46fdf7a.png">

<img width="300" alt="Bildschirmfoto 2022-08-02 um 19 33 37" src="https://user-images.githubusercontent.com/106114808/182439493-18fbfd91-d8cb-45ee-88ce-c4ed7c662ee0.png">

## Acceptance Criteria

- [x] There has to be a seperate bar to navigate
- [x] Three or four different symbols 
- [x] The symbols need to be clear to the user (I haven's decided yet which one)
- [x] Nav bar needs to be contrasted from the rest of the page

## Tasks

(for developers team)

- [x] Create feature branch
- [x] Create component
- [x] Update components
- [x] Create styled components
- [x] Add react router
- [x] Write tests
- [x] Storybook

**Comment by ahohnsen** [comment]
Hey Yvonne,

Good job! I only have one suggestion:

In my opinion you should be a bit more specific in your acceptance criteria.

> Three or four different symbols
> The symbols need to be clear to the user (I haven's decided yet which one)

With this information another developer would not be able to implement the feature. I suggest you decide first, how many icons you need and how they should look like and then you can adjust your user story accordingly (acceptance criteria and scribble). Please keep in mind, that we only want to implement features which add value to the user. Meaning, you should not add a navigation with four icons if two of them lead to empty pages. It is best to first only add the icons for the different pages you have right now and then add further icons once you really need them.

As well, I would suggest to mention in your acceptance criteria if the navigation is always visible to the user e.g. fixed to the bottom of the screen. Have you thought about highlighting the icon of the current page? If you want to implement this, you should also mention it in your acceptance criteria.
